[package]
name = "dioxus-server"
authors = ["Jonathan Kelley", "Evan Almloff"]
version = { workspace = true }
edition = "2021"
description = "Fullstack utilities for Dioxus: Build fullstack web, desktop, and mobile apps with a single codebase."
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
keywords = ["web", "desktop", "mobile", "gui", "server"]
resolver = "2"

[dependencies]
# dioxus
dioxus-core = { workspace = true }
dioxus-core-macro = { workspace = true }
dioxus-signals = { workspace = true }
dioxus-document = { workspace = true }
dioxus-html = { workspace = true }

# server functions
server_fn = { workspace = true, default-features = false, optional =  true }

# axum + native deps
axum = { workspace = true, default-features = false }
tower-http = { workspace = true, features = ["fs"], optional = true }
tokio-util = { workspace = true, features = ["rt"], optional = true }
tower = { workspace = true, features = ["util"], optional = true}
hyper-util = { workspace = true, features = ["full"], optional = true }
hyper = { workspace = true, optional = true }
http = { workspace = true }

# Dioxus + SSR
dioxus-ssr = { workspace = true }
dioxus-isrg = { workspace = true }
dioxus-router = { workspace = true, features = ["streaming"] }
dioxus-fullstack-hooks = { workspace = true }
dioxus-fullstack-protocol = { workspace = true }
dioxus-interpreter-js = { workspace = true, optional = true }

tracing = { workspace = true }
async-trait = { workspace = true }
enumset = "1.1.6"

futures-util = { workspace = true }
futures-channel = { workspace = true }
rustls = { workspace = true, optional = true }
hyper-rustls = { workspace = true, optional = true }

pin-project = { version = "1.1.10" }
thiserror = { workspace = true }
parking_lot = { workspace = true, features = ["send_guard"] }

dioxus-cli-config = { workspace = true }
dioxus-devtools = { workspace = true, optional = true }
aws-lc-rs = { version = "1.13.1", optional = true }
dioxus-history = { workspace = true }
subsecond.workspace = true
inventory = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { workspace = true, features = ["rt", "sync", "macros"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, features = ["rt", "sync", "rt-multi-thread", "macros", "net"] }

[dev-dependencies]
dioxus = { workspace = true, features = ["fullstack"] }

[features]
default = ["devtools", "full"]
full = [
    "core",
    "server_fn/ssr",
    "dep:tower-http",
    "default-tls",
    "dep:tower",
    "dep:hyper",
    "dep:tokio-util",
    "dep:hyper-util",
    "axum/default",
]
core = [
    "dep:server_fn",
    "server_fn/axum-no-default",
    "server_fn/ssr",
    "document",
]
devtools = ["dep:dioxus-devtools"]
document = ["dep:dioxus-interpreter-js"]
default-tls = ["server_fn/default-tls"]
rustls = ["server_fn/rustls", "dep:rustls", "dep:hyper-rustls"]
aws-lc-rs = ["dep:aws-lc-rs"]

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
features = ["axum", "web", "aws-lc-rs"]
